=== functionalley/BishBosh/config/bishbosh.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	AUTHOR: Dr. Alistair Ward

	Copyright (C) 2018 Dr. Alistair Ward

	This file is part of BishBosh.

	BishBosh is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	BishBosh is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with BishBosh.  If not, see <http://www.gnu.org/licenses/>.
-->
<!ELEMENT options ((evaluationOptions)?, (searchOptions)?, (ioOptions)?)>
	<!ATTLIST options
		maximumPlies	CDATA	#IMPLIED
		randomSeed	CDATA	#IMPLIED
	>
	<!ELEMENT evaluationOptions ((rankValues)*, (criteriaWeights)?, (pieceSquareTables)?)>
		<!ATTLIST evaluationOptions
			incrementalEvaluation	(False | True)	#IMPLIED
		>
		<!ELEMENT rankValues EMPTY>
			<!ATTLIST rankValues
				rank	(p | r | n | b | q | k)	#REQUIRED
				value	CDATA			#REQUIRED
			>
		<!ELEMENT criteriaWeights EMPTY>
			<!ATTLIST criteriaWeights
				material		CDATA	#IMPLIED
				mobility		CDATA	#IMPLIED
				pieceSquareValue	CDATA	#IMPLIED
				castlingPotential	CDATA	#IMPLIED
				defence			CDATA	#IMPLIED
				doubledPawns		CDATA	#IMPLIED
				isolatedPawns		CDATA	#IMPLIED
				passedPawns		CDATA	#IMPLIED
			>
		<!ELEMENT pieceSquareTables (pieceSquareTable, pieceSquareTableEndGame)>
			<!ELEMENT pieceSquareTable (byRank)+>
				<!ATTLIST pieceSquareTable
					reflectOnY	(False | True)	#IMPLIED
				>
			<!ELEMENT pieceSquareTableEndGame (byRank)+>
				<!ATTLIST pieceSquareTableEndGame
					reflectOnY	(False | True)	#IMPLIED
				>
		<!ELEMENT byRank EMPTY>
			<!ATTLIST byRank
				rank		(p | r | n | b | q | k)	#REQUIRED
				byCoordinates	CDATA			#REQUIRED
			>
	<!ELEMENT searchOptions ((transpositions)?, (standardOpeningOptions)?, searchDepthByLogicalColour)>
		<!ATTLIST searchOptions
			preferMovesTowardsCentre		(False | True)	#IMPLIED
			sortOnStandardOpeningMoveFrequency	(False | True)	#IMPLIED
			captureMoveSortAlgorithm		(MVVLVA | SEE)	#IMPLIED
			minimumHammingDistance			CDATA		#IMPLIED
			retireKillerMovesAfter			CDATA		#IMPLIED
			trapRepeatedPositions			(False | True)	#IMPLIED
			usePondering				(False | True)	#IMPLIED
		>
		<!ELEMENT standardOpeningOptions EMPTY>
			<!ATTLIST standardOpeningOptions
				tryToMatchMoves			(False | True)	#IMPLIED
				tryToMatchViaJoiningMove	(False | True)	#IMPLIED
				tryToMatchColourFlippedPosition	(False | True)	#IMPLIED
			>
		<!ELEMENT searchDepthByLogicalColour (byLogicalColour)*>
			<!ELEMENT byLogicalColour EMPTY>
				<!ATTLIST byLogicalColour
					logicalColour	(Black | White) #REQUIRED
					searchDepth	CDATA		#REQUIRED
				>
		<!ELEMENT transpositions EMPTY>
			<!ATTLIST transpositions
				retireTranspositionsAfter	CDATA	#REQUIRED
				minimumTranspositionSearchDepth	CDATA	#REQUIRED
			>
	<!ELEMENT ioOptions ((pgnOptions)*, (persistence)?, (uiOptions)?)>
		<!ATTLIST ioOptions
			outputConfigFilePath	CDATA	#IMPLIED
			maximumPGNNames		CDATA	#IMPLIED
		>
		<!ELEMENT pgnOptions (identificationTag)*>
			<!ATTLIST pgnOptions
				databaseFilePath	CDATA		#REQUIRED
				minimumPlies		CDATA		#IMPLIED
				isStrictlySequential	(False | True)	#IMPLIED
				validateMoves		(False | True)	#IMPLIED
			>
			<!ELEMENT identificationTag EMPTY>
				<!ATTLIST identificationTag
					tag	CDATA	#REQUIRED
				>
		<!ELEMENT persistence EMPTY>
			<!ATTLIST persistence
				filePath	CDATA		#REQUIRED
				automatic	(False | True)	#IMPLIED
			>
		<!ELEMENT uiOptions ((nativeUIOptions | cecpOptions)?)>
			<!ATTLIST uiOptions
				moveNotation	(Coordinate | ICCFNumeric | Smith)	#IMPLIED
				printMoveTree	CDATA					#IMPLIED
				nDecimalDigits	CDATA					#IMPLIED
				verbosity	(Silent | Normal | Verbose | Deafening)	#IMPLIED
			>
			<!ELEMENT nativeUIOptions ((boardMagnification)?, (colourScheme)?)>
				<!ELEMENT boardMagnification EMPTY>
					<!ATTLIST boardMagnification
						nRows		CDATA	#REQUIRED
						nColumns	CDATA	#REQUIRED
					>
				<!ELEMENT colourScheme EMPTY>
					<!ATTLIST colourScheme
						darkPieceColour		(Black | Red | Green | Blue | Magenta | Cyan)	#IMPLIED
						darkSquareColour	(Black | Red | Green | Blue | Magenta | Cyan)	#IMPLIED
						lightPieceColour	(Red | Green | Yellow | Magenta | Cyan | White)	#IMPLIED
						lightSquareColour	(Red | Green | Yellow | Magenta | Cyan | White)	#IMPLIED
					>
			<!ELEMENT cecpOptions (cecpFeatures)?>
				<!ATTLIST cecpOptions
					analyseMode	(False | True)	#IMPLIED
					displaySAN	(False | True)	#IMPLIED
					editMode	(False | True)	#IMPLIED
					forceMode	(False | True)	#IMPLIED
					pause		CDATA		#IMPLIED
					ponderMode	(False | True)	#IMPLIED
					postMode	(False | True)	#IMPLIED
					protocolVersion	CDATA		#IMPLIED
				>
				<!ELEMENT cecpFeatures (feature)*>
					<!ATTLIST cecpFeatures
						done	(False | True)	#IMPLIED
					>
					<!ELEMENT feature EMPTY>
						<!ATTLIST feature
							key	ID	#REQUIRED
							value	CDATA	#REQUIRED
						>

=== functionalley/BishBosh/config/Raw/bishbosh_both.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE options SYSTEM "../bishbosh.dtd">	<!-- CAVEAT: amend after relocating this file ! -->
<!--
	AUTHOR: Dr. Alistair Ward

	Copyright (C) 2018 Dr. Alistair Ward

	This file is part of BishBosh.

	BishBosh is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	BishBosh is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with BishBosh.  If not, see <http://www.gnu.org/licenses/>.
-->
<options>
	<evaluationOptions>
		<criteriaWeights material="1" mobility="0.024" pieceSquareValue="0.043" castlingPotential="0.005" defence="0" doubledPawns="0" isolatedPawns="0" passedPawns="0"/>
		<pieceSquareTables>
			<pieceSquareTable>
<!--
								a1   b1   c1   d1   a2   b2   c2   d2   a3   b3   c3   d3   a4   b4   c4   d4   a5   b5   c5   d5   a6   b6   c6   d6   a7   b7   c7   d7   a8   b8   c8   d8
-->
				<byRank rank="p" byCoordinates="0.50 0.50 0.50 0.50 0.55 0.60 0.60 0.30 0.55 0.45 0.40 0.50 0.50 0.50 0.50 0.70 0.55 0.55 0.60 0.75 0.60 0.60 0.70 0.80 1.00 1.00 1.00 1.00 0.50 0.50 0.50 0.50"/>
				<byRank rank="r" byCoordinates="0.50 0.50 0.50 0.55 0.45 0.50 0.50 0.50 0.45 0.50 0.50 0.50 0.45 0.50 0.50 0.50 0.45 0.50 0.50 0.50 0.45 0.50 0.50 0.50 0.55 0.60 0.60 0.60 0.50 0.50 0.50 0.50"/>
				<byRank rank="n" byCoordinates="0.00 0.10 0.20 0.20 0.10 0.30 0.50 0.55 0.20 0.55 0.60 0.65 0.20 0.50 0.65 0.70 0.20 0.55 0.65 0.70 0.20 0.50 0.60 0.65 0.10 0.30 0.50 0.50 0.00 0.10 0.20 0.20"/>
				<byRank rank="b" byCoordinates="0.30 0.40 0.40 0.40 0.40 0.55 0.50 0.50 0.40 0.60 0.60 0.60 0.40 0.50 0.60 0.60 0.40 0.55 0.55 0.60 0.40 0.50 0.55 0.60 0.40 0.50 0.50 0.50 0.30 0.40 0.40 0.40"/>
				<byRank rank="q" byCoordinates="0.30 0.40 0.40 0.45 0.40 0.50 0.50 0.50 0.40 0.50 0.55 0.55 0.45 0.50 0.55 0.55 0.45 0.50 0.55 0.55 0.40 0.50 0.55 0.55 0.40 0.50 0.50 0.50 0.30 0.40 0.40 0.45"/>
				<byRank rank="k" byCoordinates="0.70 0.80 0.60 0.50 0.70 0.70 0.50 0.50 0.40 0.30 0.30 0.30 0.30 0.20 0.20 0.10 0.20 0.10 0.10 0.00 0.20 0.10 0.10 0.00 0.20 0.10 0.10 0.00 0.20 0.10 0.10 0.00"/>
			</pieceSquareTable>
			<pieceSquareTableEndGame>
				<byRank rank="p" byCoordinates="0.50 0.50 0.50 0.50 0.00 0.00 0.00 0.00 0.10 0.10 0.10 0.10 0.20 0.20 0.20 0.20 0.30 0.30 0.30 0.30 0.60 0.60 0.60 0.60 1.00 1.00 1.00 1.00 0.50 0.50 0.50 0.50"/>
				<byRank rank="k" byCoordinates="0.00 0.20 0.20 0.20 0.20 0.20 0.50 0.50 0.20 0.40 0.70 0.80 0.20 0.40 0.80 0.90 0.20 0.40 0.80 0.90 0.20 0.40 0.70 0.80 0.20 0.30 0.40 0.50 0.00 0.10 0.20 0.30"/>
			</pieceSquareTableEndGame>
		</pieceSquareTables>
	</evaluationOptions>
	<searchOptions preferMovesTowardsCentre="False" sortOnStandardOpeningMoveFrequency="True" captureMoveSortAlgorithm="MVVLVA" retireKillerMovesAfter="3">
		<transpositions retireTranspositionsAfter="1" minimumTranspositionSearchDepth="2"/>
		<searchDepthByLogicalColour>
			<byLogicalColour logicalColour="Black" searchDepth="4"/>
			<byLogicalColour logicalColour="White" searchDepth="4"/>
		</searchDepthByLogicalColour>
	</searchOptions>
	<ioOptions maximumPGNNames="8">
		<pgnOptions databaseFilePath="pgn/scid.pgn" isStrictlySequential="False" validateMoves="False">
			<identificationTag tag="ECO"/>
			<identificationTag tag="Variation"/>
		</pgnOptions>
		<uiOptions>
			<nativeUIOptions/>
		</uiOptions>
	</ioOptions>
</options>

=== functionalley/BishBosh/config/Raw/bishbosh_duel_white.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE options SYSTEM "../bishbosh.dtd">	<!-- CAVEAT: amend after relocating this file ! -->
<!--
	AUTHOR: Dr. Alistair Ward

	Copyright (C) 2021 Dr. Alistair Ward

	This file is part of BishBosh.

	BishBosh is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	BishBosh is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with BishBosh.  If not, see <http://www.gnu.org/licenses/>.
-->
<!--
	* The purpose of this config-file is to permit a duel between two instances of bishbosh, to facilitate comparison between configurations.

	* CAVEAT: White has a natural advantage.
-->
<options>
	<evaluationOptions>
		&rankValues_Kaufman;
		<criteriaWeights material="1" mobility="0" pieceSquareValue="0.1" castlingPotential="0" defence="0" doubledPawns="0" isolatedPawns="0" passedPawns="0"/>	<!-- N.B. only those criteria under test need be non-zero -->
		&pieceSquareTables_symmetric;
	</evaluationOptions>
	<searchOptions captureMoveSortAlgorithm="MVVLVA" retireKillerMovesAfter="3" usePondering="False">	<!-- CAVEAT: pondering uses time more productively used by the other instance -->
		&transpositions;
		<searchDepthByLogicalColour>
			<byLogicalColour logicalColour="White" searchDepth="3"/>
		</searchDepthByLogicalColour>
	</searchOptions>
	<ioOptions>
		&pgnOptions_SCID;	<!-- CAVEAT: specification of a PGN-database is required for non-determininstic behaviour -->
		<persistence filePath="/dev/null" automatic="False"/>	<!-- CAVEAT: otherwise the game may already have started -->
		<uiOptions moveNotation="Smith">	<!-- CAVEAT: coordinate with the opponent defined in 'bishbosh_duel_black.txt' & 'bishbosh.cabal' -->
			<nativeUIOptions/>
		</uiOptions>
	</ioOptions>
</options>

=== functionalley/BishBosh/config/CECP/bishbosh_black.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE options SYSTEM "../bishbosh.dtd">	<!-- CAVEAT: amend after relocating this file ! -->
<!--
	AUTHOR: Dr. Alistair Ward

	Copyright (C) 2018 Dr. Alistair Ward

	This file is part of BishBosh.

	BishBosh is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	BishBosh is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with BishBosh.  If not, see <http://www.gnu.org/licenses/>.
-->
<options>
	<evaluationOptions>
		&rankValues_Kaufman;
		&criteriaWeights;
		&pieceSquareTables_symmetric;
	</evaluationOptions>
	<searchOptions captureMoveSortAlgorithm="MVVLVA" retireKillerMovesAfter="3" sortOnStandardOpeningMoveFrequency="True" usePondering="True">
		&transpositions;
		&standardOpeningOptions;
		<searchDepthByLogicalColour>
			<byLogicalColour logicalColour="Black" searchDepth="5"/>
		</searchDepthByLogicalColour>
	</searchOptions>
	<ioOptions maximumPGNNames="8">
		&pgnOptions_SCID;
		<persistence filePath="/dev/null" automatic="False"/>	<!-- replace *nix-specific path with 'nul' in Windows ? -->
		<uiOptions moveNotation="PureCoordinate" verbosity="Silent">
			<cecpOptions/>
		</uiOptions>
	</ioOptions>
</options>

=== functionalley/BishBosh/config/Raw/bishbosh_prof.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE options SYSTEM "../bishbosh.dtd">	<!-- CAVEAT: amend after relocating this file ! -->
<!--
	AUTHOR: Dr. Alistair Ward

	Copyright (C) 2018 Dr. Alistair Ward

	This file is part of BishBosh.

	BishBosh is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	BishBosh is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with BishBosh.  If not, see <http://www.gnu.org/licenses/>.
-->
<!-- e2e3 e7e5 c2c4 d7d6 b1c3 b8c6 b2b3 g8f6 f1d3 c6b4 d3e2 f8e7 a2a3 b4c6 f2f4 e5f4p e3f4p c6d4 g1f3 c7c5 -->
<options maximumPlies="20" randomSeed="-1">
	<evaluationOptions>
		<rankValues rank="p" value="0.1"/>
		<rankValues rank="r" value="0.5"/>
		<rankValues rank="n" value="0.3"/>
		<rankValues rank="b" value="0.3"/>
		<rankValues rank="q" value="0.9"/>
		<rankValues rank="k" value="0"/>
		<criteriaWeights material="1" mobility="0.01" pieceSquareValue="0.01" castlingPotential="0.01" defence="0.0001" doubledPawns="0.0001" isolatedPawns="0.0001" passedPawns="0.0001"/>
		<pieceSquareTables>
			<pieceSquareTable>
<!--
								a1   b1   c1   d1   a2   b2   c2   d2   a3   b3   c3   d3   a4   b4   c4   d4   a5   b5   c5   d5   a6   b6   c6   d6   a7   b7   c7   d7   a8   b8   c8   d8
-->
				<byRank rank="p" byCoordinates="0.50 0.50 0.50 0.50 0.55 0.60 0.60 0.30 0.55 0.45 0.40 0.50 0.50 0.50 0.50 0.70 0.55 0.55 0.60 0.75 0.60 0.60 0.70 0.80 1.00 1.00 1.00 1.00 0.50 0.50 0.50 0.50"/>
				<byRank rank="r" byCoordinates="0.50 0.50 0.50 0.55 0.45 0.50 0.50 0.50 0.45 0.50 0.50 0.50 0.45 0.50 0.50 0.50 0.45 0.50 0.50 0.50 0.45 0.50 0.50 0.50 0.55 0.60 0.60 0.60 0.50 0.50 0.50 0.50"/>
				<byRank rank="n" byCoordinates="0.00 0.10 0.20 0.20 0.10 0.30 0.50 0.55 0.20 0.55 0.60 0.65 0.20 0.50 0.65 0.70 0.20 0.55 0.65 0.70 0.20 0.50 0.60 0.65 0.10 0.30 0.50 0.50 0.00 0.10 0.20 0.20"/>
				<byRank rank="b" byCoordinates="0.30 0.40 0.40 0.40 0.40 0.55 0.50 0.50 0.40 0.60 0.60 0.60 0.40 0.50 0.60 0.60 0.40 0.55 0.55 0.60 0.40 0.50 0.55 0.60 0.40 0.50 0.50 0.50 0.30 0.40 0.40 0.40"/>
				<byRank rank="q" byCoordinates="0.30 0.40 0.40 0.45 0.40 0.50 0.50 0.50 0.40 0.50 0.55 0.55 0.45 0.50 0.55 0.55 0.45 0.50 0.55 0.55 0.40 0.50 0.55 0.55 0.40 0.50 0.50 0.50 0.30 0.40 0.40 0.45"/>
				<byRank rank="k" byCoordinates="0.70 0.80 0.60 0.50 0.70 0.70 0.50 0.50 0.40 0.30 0.30 0.30 0.30 0.20 0.20 0.10 0.20 0.10 0.10 0.00 0.20 0.10 0.10 0.00 0.20 0.10 0.10 0.00 0.20 0.10 0.10 0.00"/>
			</pieceSquareTable>
			<pieceSquareTableEndGame>
				<byRank rank="p" byCoordinates="0.50 0.50 0.50 0.50 0.00 0.00 0.00 0.00 0.10 0.10 0.10 0.10 0.20 0.20 0.20 0.20 0.30 0.30 0.30 0.30 0.60 0.60 0.60 0.60 1.00 1.00 1.00 1.00 0.50 0.50 0.50 0.50"/>
				<byRank rank="k" byCoordinates="0.00 0.20 0.20 0.20 0.20 0.20 0.50 0.50 0.20 0.40 0.70 0.80 0.20 0.40 0.80 0.90 0.20 0.40 0.80 0.90 0.20 0.40 0.70 0.80 0.20 0.30 0.40 0.50 0.00 0.10 0.20 0.30"/>
			</pieceSquareTableEndGame>
		</pieceSquareTables>
	</evaluationOptions>
	<searchOptions preferMovesTowardsCentre="False" sortOnStandardOpeningMoveFrequency="True" captureMoveSortAlgorithm="MVVLVA" retireKillerMovesAfter="3">
		<transpositions retireTranspositionsAfter="1" minimumTranspositionSearchDepth="2"/>
		<searchDepthByLogicalColour>
			<byLogicalColour logicalColour="Black" searchDepth="4"/>
			<byLogicalColour logicalColour="White" searchDepth="4"/>
		</searchDepthByLogicalColour>
	</searchOptions>
	<ioOptions maximumPGNNames="8">
		<pgnOptions databaseFilePath="pgn/scid_fr.pgn" validateMoves="True">
			<identificationTag tag="ECO"/>
			<identificationTag tag="Variation"/>
		</pgnOptions>
		<persistence filePath="/dev/null" automatic="False"/>	<!-- replace *nix-specific path with 'nul' in Windows ? -->
		<uiOptions verbosity="Silent"/>
	</ioOptions>
</options>
